### ISSUE TITLE
Potential naming clash

### ISSUE THREAD

**Issue by swalladge** [jonhadfield/sncli#1]
Firstly, awesome project! It's great to start seeing more projects building off standardnote. :+1:

Anyway, just wanted to give you a heads up: there's a command line client for Simplenote also called sncli ( https://github.com/insanum/sncli/ ) that's been around for a while. No pressure to rename anything, just something to be aware of, especially when planning distribution/packages.

**Comment by jonhadfield** [comment]
I guess it's only fair for me to rename. Will do asap.
Thanks for letting me know.

**Comment by swalladge** [comment]
Thanks. :) I could see some confusion arising from two different cli notetaking tools with the same name.
